pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                echo 'Checking source code'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t devops-demo:latest .'
            }
        }

        stage('Run Container') {
            steps {
                sh 'docker rm -f devops-demo 2>/dev/null || true'
                sh 'docker run -d --name devops-demo --network jenkins-ci -p 8085:80 devops-demo:latest'
            }
        }

        stage('Test') {
            steps {
                sh 'curl -f http://devops-demo'
            }
        }
    }
}
